org: adibtatriantama
app: image-search-abstraction-layer
service: image-search-abstraction-layer

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt:
            - MainTable
            - Arn

  environment:
    TABLE_NAME:
      Ref: MainTable

functions:
  # USER
  check:
    handler: src/useCase/check/handler.main
    events:
      - httpApi:
          path: /check
          method: get

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'PK'
            AttributeType: 'S'
          - AttributeName: 'SK'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'PK'
            KeyType: 'HASH'
          - AttributeName: 'SK'
            KeyType: 'RANGE'
        BillingMode: 'PAY_PER_REQUEST'
        TimeToLiveSpecification:
          AttributeName: expireAt
          Enabled: true
