org: adibtatriantama
app: image-search-abstraction-layer
service: image-search-abstraction-layer
frameworkVersion: ^3.25.1

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'PK'
            AttributeType: 'S'
          - AttributeName: 'SK'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'PK'
            KeyType: 'HASH'
          - AttributeName: 'SK'
            KeyType: 'RANGE'
        BillingMode: 'PAY_PER_REQUEST'
        TimeToLiveSpecification:
          AttributeName: expireAt
          Enabled: true

outputs:
  tableName:
    Ref: MainTable
  appRegion: ${aws:region}
